# Generated by Django 2.2 on 2019-10-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20191023_1428'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='posted',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('slug', 'organization')},
        ),
    ]
