# Generated by Django 2.2 on 2019-10-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20191028_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='channel',
            field=models.ForeignKey(help_text='What channel does the alert belong to?', on_delete=django.db.models.deletion.CASCADE, to='alerts.Channel'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='content',
            field=models.TextField(help_text='What is the content of the alert? We recommend keeping this under 250 characters.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='image_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='url',
            field=models.URLField(blank=True, help_text='Where should subscribers go when they click on the alert? (Usually, this is the link to the associated news story on your website.)'),
        ),
    ]
