# Generated by Django 2.2 on 2019-11-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20191029_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source_identifier',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('TWITTER', 'Twitter')], max_length=10)),
                ('identifier', models.TextField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('source', 'source_identifier')},
        ),
    ]
