# Generated by Django 2.2 on 2019-11-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20191113_1626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('source', 'identifier')},
        ),
    ]
