# Generated by Django 2.2 on 2019-11-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20191113_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='human_readable_identifier',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='identifier',
            field=models.TextField(null=True),
        ),
    ]
