# Generated by Django 3.0 on 2019-12-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20191203_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webpush_sends', models.BigIntegerField(default=0)),
                ('webpush_clicks', models.BigIntegerField(default=0)),
                ('email_sends', models.BigIntegerField(default=0)),
                ('email_clicks', models.BigIntegerField(default=0)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alerts.Alert')),
            ],
        ),
    ]
