# Generated by Django 2.2 on 2019-10-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_auto_20191023_1428'),
        ('alerts', '0002_auto_20191028_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('channels', models.ManyToManyField(to='alerts.Channel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Organization')),
            ],
        ),
    ]
