# Generated by Django 2.2 on 2019-10-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20191030_1642'),
        ('webpush', '0002_auto_20190603_0005'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebpushSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpush.PushInformation')),
            ],
        ),
    ]
