# Generated by Django 2.2 on 2019-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('presspass_uuid', models.UUIDField()),
                ('website', models.URLField(blank=True, default='')),
            ],
        ),
    ]
