# Generated by Django 2.2 on 2019-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='presspass_uuid',
            field=models.UUIDField(editable=False),
        ),
    ]
