# Generated by Django 2.2 on 2019-10-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20191029_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='custom_hostname',
            field=models.TextField(blank=True, help_text="Your organization's custom hostname (domain) for OpenAlerts. If you don't know what this means, just ignore this setting.", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text="The URL of your news organization's logo (for use on public facing pages). This image will be shown on a white background."),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#444444', help_text="Your news organization's primary brand color. Text will be shown in this color, so it should be relatively dark.", max_length=7),
        ),
    ]
