# Generated by Django 3.0 on 2019-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_organization_head_inject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='head_inject',
            field=models.TextField(blank=True, default='', help_text='Custom data to insert inside the HTML `head` on public-facing pages.'),
        ),
    ]
